### ISSUE TITLE
Module does not create backup file in $ANSIBLE_LOCAL_BACKUP

### ISSUE THREAD

**Issue by fthommen** [bcoca/local_backup#2]
This playbook as described in the README:

```
- hosts: HOST
  gather_facts: false
  roles:
    - local_backup
  tasks:
    - copy: backup=yes src=testfile dest=/etc/testfile
```

does not create the backup file in `/tmp` when run as
```
ansible-playbook  ./test.yml -e "ANSIBLE_LOCAL_BACKUP=/tmp" --user=root
```
Instead the backup file is created as usual as `/etc/testfile.$PID.$TIMESTAMP`.

Ansible version is 2.9.17 on CentOS 7.9.  Wrong usage?
